export { default as HomePage } from './HomePage';
export { default as ProductsPage } from './ProductsPage';
// export { default as ProductDetailPage } from './ProductDetailPage';
// export { default as NotFoundPage } from './NotFoundPage';
// export { default as CartPage } from './CartPage';
// export { default as CustomerInfoPage } from './CustomerInfoPage';
// export { default as LoginBackendPage } from './LoginBackendPage';
// // export { default as ProductDetailPageBySide } from './ProductDetailPageBySide';
// export { default as CheckoutFormPage } from './CheckoutFormPage';
// export { default as OrderListsPage } from './OrderListsPage';
// export { default as CheckoutPaymentPageFromOrders } from './CheckoutPaymentPageFromOrders';
export { default as ProductsPageFromWishList } from './ProductsPageFromWishList';
